const RARITY={COMMON:'#aaa',UNCOMMON:'#55ff55',RARE:'#55aaff',EPIC:'#aa55ff',LEGENDARY:'#ffaa00',MYTHIC:'#ff55ff',DIVINE:'#55ffff',SUPREME:'#ff5555',VERY_SPECIAL:'#ff5555'};
const STATS={strength:'Strength',critChance:'Crit Chance',critDamage:'Crit Damage',intelligence:'Intelligence',health:'Health',defence:'Defense',speed:'Speed',ferocity:'Ferocity',magicFind:'Magic Find',attackSpeed:'Attack Speed'};
const MATERIALS=['DIAMOND_SWORD','NETHERITE_SWORD','DIAMOND_AXE','NETHERITE_AXE','DIAMOND_PICKAXE','NETHERITE_PICKAXE','DIAMOND_HELMET','DIAMOND_CHESTPLATE','DIAMOND_LEGGINGS','DIAMOND_BOOTS','NETHERITE_HELMET','NETHERITE_CHESTPLATE','NETHERITE_LEGGINGS','NETHERITE_BOOTS','BOW','CROSSBOW','TRIDENT','SHIELD','FISHING_ROD','DIAMOND','NETHERITE_INGOT','GOLDEN_APPLE','ENDER_PEARL','STICK'];
const ENCHANTMENTS=['sharpness','critical','smite','bane_of_arthropods','looting','fire_aspect','knockback','sweeping_edge','protection','growth','feather_falling','depth_strider','respiration','aqua_affinity','thorns','unbreaking','efficiency','fortune','silk_touch','power','punch','flame','infinity','mending','blast_protection','projectile_protection'];
const $=id=>document.getElementById(id);
const ids=['displayName','category','rarity','itemId','material','lore','source','url',...Object.keys(STATS),'enchantments','abilityName','abilityDescription','abilityMana'];
const STORAGE='skyblock-item-studio';
function data(){const d={};ids.forEach(id=>{const e=$(id);d[id]=e?e.value:''});d.unbreakable=!!$('unbreakable')?.checked;d.glint=!!$('glint')?.checked;d.customData=$('customData')?.value||'';return d}
function escape(s){return String(s??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function statLines(d){return Object.entries(STATS).filter(([k])=>Number(d[k])).map(([k,n])=>`<div class="tip-stat"><b>${n}:</b> ${escape(d[k])}</div>`).join('')}
function preview(){const d=data(),name=d.displayName||'Your Custom Item',rarity=d.rarity||'EPIC';let html=`<div class="tip-name" style="color:${RARITY[rarity]}">${escape(name)}</div><div class="tip-rarity">${rarity}${d.category?' · '+escape(d.category):''}</div>${statLines(d)}`;if(d.lore)html+=`<div class="tip-lore">${escape(d.lore)}</div>`;if(d.enchantments)html+=`<div class="tip-lore"><b>Enchantments</b><br>${escape(d.enchantments)}</div>`;if(d.abilityName)html+=`<div class="tip-ability"><b style="color:#55aaff">${escape(d.abilityName)}</b>${d.abilityMana?` <span style="color:#55aaff">(${d.abilityMana} Mana)</span>`:''}<br>${escape(d.abilityDescription||'Custom ability')}</div>`;if(d.source)html+=`<div class="tip-lore">${escape(d.source)}</div>`;if(d.glint)html+=`<div class="tip-lore" style="color:#55ffff">✦ Enchantment Glint</div>`;$('tooltip').innerHTML=html}
function java(d){const cls=(d.displayName||'CustomItem').replace(/[^a-zA-Z0-9]/g,'')||'CustomItem';let out=`package me.godspunky.skyblock.features.item.${(d.category||'other').toLowerCase()};\n\npublic class ${cls} {\n    public static final String ID = "${d.itemId||cls.toUpperCase()}";\n    public static final String MATERIAL = "${(d.material||'DIAMOND').toUpperCase()}";\n    public static final String NAME = "${String(d.displayName||'Custom Item').replace(/"/g,'\\"')}";\n    public static final String RARITY = "${d.rarity}";\n`;Object.entries(STATS).forEach(([k])=>{if(Number(d[k]))out+=`    public static final double ${k.toUpperCase()} = ${d[k]};\n`});if(d.lore)out+=`    public static final String LORE = "${d.lore.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/"/g,'\\"')}";\n`;if(d.enchantments)out+=`    public static final String ENCHANTMENTS = "${d.enchantments.replace(/"/g,'\\"')}";\n`;if(d.abilityName)out+=`    public static final String ABILITY = "${d.abilityName.replace(/"/g,'\\"')}";\n`;if(d.unbreakable)out+='    public static final boolean UNBREAKABLE = true;\n';if(d.glint)out+='    public static final boolean ENCHANTMENT_GLINT = true;\n';return out+'}'}
function json(d){return JSON.stringify({...d,stats:Object.fromEntries(Object.entries(STATS).filter(([k])=>Number(d[k])).map(([k])=>[k,Number(d[k])]))},null,2)}
function componentText(d){const c=[];if(d.displayName)c.push(`custom_name={text:'${String(d.displayName).replace(/'/g,"\\'")}'}`);if(d.lore){const lines=d.lore.split(/\n/).filter(Boolean).map(x=>`{text:'${x.replace(/'/g,"\\'")}'}`);if(lines.length)c.push(`lore=[${lines.join(',')}]`)}if(d.enchantments){const levels={};d.enchantments.split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>{const [n,l]=x.split(':');if(n)levels[n.trim()]=Math.max(0,Math.min(255,Number(l)||1))});if(Object.keys(levels).length)c.push(`enchantments={${Object.entries(levels).map(([k,v])=>`${k}:${v}`).join(',')}}`)}if(d.unbreakable)c.push('unbreakable={}');if(d.glint)c.push('enchantment_glint_override=true');if(d.customData){try{const obj=JSON.parse(d.customData);c.push(`custom_data=${JSON.stringify(obj).replace(/"/g,"'")}`)}catch{}}return c.join(',')}
function command(d){const material=(d.material||'diamond').toLowerCase().replace(/^minecraft:/,'');const components=componentText(d);return `/give @p minecraft:${material}${components?`[${components}]`:''} 1`}
function setOutput(text){$('output').textContent=text}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(data()));if($('saveState'))$('saveState').textContent='● Saved locally'}
function restore(d){try{d=d||JSON.parse(localStorage.getItem(STORAGE));if(!d)return;ids.forEach(id=>{if($(id)&&d[id]!=null)$(id).value=d[id]});if($('unbreakable'))$('unbreakable').checked=!!d.unbreakable;if($('glint'))$('glint').checked=!!d.glint;if($('customData'))$('customData').value=d.customData||''}catch{}}
function randomize(){const names=['Starforged Blade','Voidpiercer','Celestial Crown','Aether Staff','Dragonheart','Frostbite','Shadowfang'];const categories=['Weapon','Armor','Accessory','Tool'];const rarities=Object.keys(RARITY);$('displayName').value=names[Math.floor(Math.random()*names.length)];$('rarity').value=rarities[Math.floor(Math.random()*rarities.length)];$('category').value=categories[Math.floor(Math.random()*categories.length)];$('material').value=$('category').value==='Weapon'?'DIAMOND_SWORD':$('category').value==='Armor'?'DIAMOND_CHESTPLATE':'DIAMOND';$('itemId').value=$('displayName').value.toUpperCase().replace(/[^A-Z0-9]+/g,'_');$('strength').value=Math.floor(Math.random()*201);$('critDamage').value=Math.floor(Math.random()*301);$('intelligence').value=Math.floor(Math.random()*501);$('lore').value='A mysterious custom item.\n\n§7Generated with SkyBlock Item Studio.';preview();save();toast('Random item created')}
function reset(){localStorage.removeItem(STORAGE);$('itemForm').reset();$('material').value='DIAMOND_SWORD';if($('unbreakable'))$('unbreakable').checked=false;if($('glint'))$('glint').checked=false;preview();setOutput('// Your generated code will appear here.');toast('Item reset')}
function download(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function generate(kind='java'){const d=data();const text=kind==='json'?json(d):kind==='command'?command(d):java(d);setOutput(text);return text}
function injectStyles(){const s=document.createElement('style');s.textContent=`.studio-tools{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:12px 0}.studio-tools button,.add-btn,.remove-btn,.preset-row button{background:#121923;border:1px solid #253040;color:#e7edf7;border-radius:9px;padding:9px 10px;cursor:pointer;font-size:11px}.studio-tools button:hover,.add-btn:hover{border-color:#45b8ff}.advanced-box{margin-top:10px;border-top:1px solid #253040;padding-top:12px}.preset-panel{background:#101722;border:1px solid #253040;border-radius:14px;padding:14px;margin-top:12px}.preset-row{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #202b39;font-size:12px}.preset-row:last-child{border-bottom:0}.preset-actions{display:flex;gap:5px}.enchant-row{display:grid;grid-template-columns:1fr 90px 34px;gap:7px;margin:7px 0}.enchant-row select,.enchant-row input,.ability-row input,.ability-row textarea{width:100%;border:1px solid #273345;background:#0a0f16;color:#e7edf7;border-radius:8px;padding:9px;font:inherit;font-size:12px}.ability-row{display:grid;grid-template-columns:1fr 90px 1fr 34px;gap:7px;margin:7px 0}.subtext{color:#8995a8;font-size:11px;margin:5px 0 0}.check{display:flex;align-items:center;gap:8px;color:#aeb9c9;font-size:12px;margin-bottom:12px}.check input{accent-color:#45b8ff}@media(max-width:600px){.studio-tools{grid-template-columns:1fr 1fr}.enchant-row{grid-template-columns:1fr 75px 32px}.ability-row{grid-template-columns:1fr 75px 1fr 32px}}`;document.head.appendChild(s)}
function addAdvancedUI(){const previewPanel=document.querySelector('.preview-panel');if(!previewPanel||$('studioTools'))return;const tools=document.createElement('div');tools.id='studioTools';tools.className='studio-tools';tools.innerHTML='<button id="savePreset">💾 Save preset</button><button id="openPresets">📚 Presets</button><button id="shareItem">🔗 Share item</button><button id="importItem">📥 Import JSON</button><input id="importJsonFile" type="file" accept="application/json" hidden>';const exportCard=previewPanel.querySelector('.export-card');previewPanel.insertBefore(tools,exportCard);const panel=document.createElement('div');panel.id='presetPanel';panel.className='preset-panel';panel.hidden=true;panel.innerHTML='<div class="section-title"><span>Saved presets</span><button id="closePresets" class="remove-btn">Close</button></div><div id="presetList"></div>';previewPanel.insertBefore(panel,previewPanel.querySelector('.code-card'));const advanced=document.createElement('div');advanced.className='advanced-box';advanced.innerHTML='<div class="section-title"><span>Advanced item data</span><small>1.21+ components</small></div><label class="check"><input id="unbreakable" type="checkbox"> Unbreakable</label><label class="check"><input id="glint" type="checkbox"> Force enchantment glint</label><div class="field"><label for="customData">Custom data JSON</label><textarea id="customData" rows="4" placeholder="{&quot;custom_id&quot;:&quot;MY_ITEM&quot;}"></textarea></div>';const form=document.getElementById('itemForm');const last=form?.lastElementChild;if(last)last.appendChild(advanced)}
function buildEnchantments(){const input=$('enchantments');if(!input||$('enchantBuilder'))return;const wrap=document.createElement('div');wrap.id='enchantBuilder';wrap.innerHTML='<div class="field"><label>Visual enchantment builder</label><div id="enchantRows"></div><button type="button" class="add-btn" id="addEnchant">＋ Add enchantment</button></div>';input.parentElement.parentElement.insertAdjacentElement('afterend',wrap);const rows=$('enchantRows');function add(name='sharpness',level=5){const r=document.createElement('div');r.className='enchant-row';r.innerHTML=`<select>${ENCHANTMENTS.map(x=>`<option ${x===name?'selected':''}>${x}</option>`).join('')}</select><input type="number" min="1" max="255" value="${level}"><button type="button" class="remove-btn">×</button>`;r.querySelector('button').onclick=()=>{r.remove();sync()};r.querySelectorAll('select,input').forEach(e=>e.oninput=sync);rows.appendChild(r);sync()}function sync(){const vals=[...rows.children].map(r=>`${r.children[0].value}:${r.children[1].value}`);input.value=vals.join(', ');preview();save()}$('addEnchant').onclick=()=>add();add('sharpness',5)}
function buildAbilities(){const name=$('abilityName'),desc=$('abilityDescription'),mana=$('abilityMana');if(!name||$('abilityBuilder'))return;const wrap=document.createElement('div');wrap.id='abilityBuilder';wrap.innerHTML='<div class="field"><label>Quick ability builder</label><div id="abilityRows"></div><button type="button" class="add-btn" id="addAbility">＋ Add ability</button></div>';desc.parentElement.parentElement.insertAdjacentElement('afterend',wrap);const rows=$('abilityRows');function add(n=name.value||'WITHER IMPACT',m=mana.value||100,d=desc.value||'Teleport 10 blocks ahead and deal damage.'){const r=document.createElement('div');r.className='ability-row';r.innerHTML=`<input placeholder="Ability name" value="${escape(n)}"><input type="number" min="0" value="${m}"><input placeholder="Description" value="${escape(d)}"><button type="button" class="remove-btn">×</button>`;r.querySelector('button').onclick=()=>r.remove();rows.appendChild(r)}$('addAbility').onclick=()=>add('NEW ABILITY',100,'Describe what the ability does.');add()}
function presets(){const key='skyblock-presets';const get=()=>JSON.parse(localStorage.getItem(key)||'{}');function render(){const p=$('presetPanel'),list=$('presetList');if(!p||!list)return;const all=get();list.innerHTML=Object.keys(all).length?Object.keys(all).map(n=>`<div class="preset-row"><span>${escape(n)}</span><span class="preset-actions"><button data-load="${encodeURIComponent(n)}">Load</button><button data-del="${encodeURIComponent(n)}">Delete</button></span></div>`).join(''):'<small style="color:#8995a8">No presets saved yet.</small>';list.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{restore(all[decodeURIComponent(b.dataset.load)]);preview();save();toast('Preset loaded')});list.querySelectorAll('[data-del]').forEach(b=>{b.onclick=()=>{delete all[decodeURIComponent(b.dataset.del)];localStorage.setItem(key,JSON.stringify(all));render()}})}$('savePreset').onclick=()=>{const name=prompt('Preset name:',data().displayName||'My Item');if(name){const all=get();all[name]=data();localStorage.setItem(key,JSON.stringify(all));render();toast('Preset saved')}};$('openPresets').onclick=()=>{$('presetPanel').hidden=!$('presetPanel').hidden;render()};$('closePresets').onclick=()=>{$('presetPanel').hidden=true};render()}
function sharing(){const d=data();const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(d))));const url=`${location.origin}${location.pathname}#item=${encoded}`;history.replaceState(null,'',`#item=${encoded}`);navigator.clipboard?.writeText(url);toast('Share link copied')}
function importExport(){const file=$('importJsonFile');$('importItem').onclick=()=>file.click();file.onchange=async()=>{const f=file.files[0];if(!f)return;try{restore(JSON.parse(await f.text()));preview();save();toast('Item imported')}catch{toast('Invalid JSON file')}file.value=''} }
function loadHash(){const m=location.hash.match(/^#item=(.+)$/);if(!m)return;try{restore(JSON.parse(decodeURIComponent(escape(atob(m[1])))));preview();save()}catch{}}
document.addEventListener('DOMContentLoaded',()=>{injectStyles();addAdvancedUI();buildEnchantments();buildAbilities();restore();loadHash();preview();ids.forEach(id=>$(id)?.addEventListener('input',()=>{preview();save()}));$('generateBtn').onclick=()=>{generate();toast('Java output generated')};$('copyCodeBtn').onclick=()=>navigator.clipboard.writeText($('output').textContent).then(()=>toast('Copied output'));$('copyPreviewBtn').onclick=()=>navigator.clipboard.writeText(($('displayName').value||'Custom Item')+'\n'+$('tooltip').innerText).then(()=>toast('Tooltip copied'));$('randomBtn').onclick=randomize;$('resetBtn').onclick=reset;document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const k=b.dataset.export;if(k==='download'){download(generate('java'),'custom-item.java');toast('Java file downloaded')}else{setOutput(generate(k));toast(`${k.toUpperCase()} generated`)}});presets();$('shareItem').onclick=sharing;importExport();toast('Studio ready')});
